### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by jakevinolo** [saullocastro/cubature#35] opened 2023-05-19 09:23 UTC
Dear Dr. Castro,
thanks to provide your wrapper for cubature. 
I try to use it with Spyder 3.3.6 on a Linx Mint (Linux cudaknight 5.15.0-72-generic #79~20.04.1-Ubuntu).
All the requirements seem to be fulfilled on my machine. I did:
 
_p_ython3 -m pip install cubature
Requirement already satisfied: cubature in ./.local/lib/python3.8/site-packages (0.16.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from cubature) (1.17.4)
Requirement already satisfied: cython in /usr/lib/python3/dist-packages (from cubature) (0.29.14)__

If I try to run the example ex_areas.py I get the following ValueError:

File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jakevinolo/Dokumente/Conformity_IEC_Behrens/Berechnungen/cubature-master_Python/examples/ex_areas.py", line 4, in <module>
    from cubature import cubature

  File "/home/jakevinolo/.local/lib/python3.8/site-packages/cubature/__init__.py", line 41, in <module>
    from .cubature import *

  File "/home/jakevinolo/.local/lib/python3.8/site-packages/cubature/cubature.py", line 3, in <module>
    from ._cubature import cubature as _cython_cubature

  File "cubature/_cubature.pyx", line 1, in init cubature._cubature

**ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject**

I checked the issue list but I couldn't find this issue (maybe it's something very simple that I am overlooking). 

Can you help me?

Thanks in advance.

**Comment by saullocastro** [comment] 2023-05-24 07:16
Dear @jakevinolo , I can reproduce your bug here. I know where the issue is, and it is related to NumPy's C API, more specifically with an incompatibility between different NumPy versions. I will remove the dependency from NumPy C API by adopting the use of memoryviews. More info to come soon...

**Comment by saullocastro** [comment] 2023-05-24 22:31
Fixed with release 0.17.2

**Closed by saullocastro** 2023-05-24 22:31 UTC
Labels: bug
